### ISSUE TITLE
[Feature] Start, Pause, Stop Recording/Capturing GUI

### ISSUE THREAD

**Issue by dimitrieh** [cytopia/ffscreencast#10]
As seen on this screencast:

![screencast](https://cloud.githubusercontent.com/assets/429659/14770168/1fc276cc-0a6b-11e6-9090-a7cd7979cf91.gif)

It would be awesome to be able to first select a screen region, so you can set-up everything and begin recording accordingly! starting, pause, starting again and stopping it.

**Comment by cytopia** [comment]
Start, stop and pause is not going to be possible (at least not that I know of it), as I am simply triggering ffmpeg and haven't heard that you could stop/resume on that. It only shows `q` for quit :-)

I will close it, as it won't be possible.
The partial screen capture however might be possible (#5)

**Comment by dimitrieh** [comment]
Got ya!

Op do 19 mei 2016 22:28 schreef cytopia <notifications@github.com>:

> Start, stop and pause is not going to be possible (at least not that I
> know of it), as I am simply triggering ffmpeg and haven't heard that you
> could stop/resume on that. It only shows q for quit :-)
>
> I will close it, as it won't be possible.
> The partial screen capture however might be possible (#5
> <https://github.com/cytopia/ffscreencast/issues/5>)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cytopia/ffscreencast/issues/10#issuecomment-220438983>
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>
