### ISSUE TITLE
install with brew?

### ISSUE THREAD

**Issue by strages** [cytopia/ffscreencast#4]
Hi I can't get it to work yet (how to install?), possible to get a brew install command?

**Comment by cytopia** [comment]
Hi @strages,

There is currently no brew (OSX) or any other packet (linux, bsd) available.

What you need to do is clone the repository:

```shell
git clone https://github.com/cytopia/ffscreencast
cd ffscreencast

# copy binary to system
sudo cp bin/ffscreencast /usr/local/bin
# or to your local bin dir (if it exists)
cp bin/ffscreencast ~/bin
```

During the first start it will also create a configuration file in: `~/.config/ffscreencast/ffscreencastrc` where you can alter default values.

**Comment by cytopia** [comment]
Anybody willing to add this to [homebrew](http://brew.sh/)?

**Comment by cytopia** [comment]
Brew install command added  `brew install cytopia/tap/ffscreencast`

Still awaiting official homebrew package (`brew install ffscreencast`). Hopefully it will be added soon.

**Comment by strages** [comment]
nice
