### ISSUE TITLE
[Feature] partial screencapture

### ISSUE THREAD

**Issue by dimitrieh** [cytopia/ffscreencast#5]
It would be great to select a part of the screen to record (to get it into another CLI or with within this app > for gif output)

**Comment by cytopia** [comment]
As this is a cli program, I still haven't figured out how to do that best to still be user friendly, but also not make too much use of the mouse.

Any recommendations for how it should be done are welcome... use window id or select window via mouse or select portion of screen via mouse...

Best would be an option to tell the program via parameter what to do... Any hints?

**Comment by strages** [comment]
hi, thanks for your reply.. the point is i have found similar programs such as your in the past, but never got them working due to X11 (always gave me errors while executing make).  

See: 
- https://github.com/lolilolicon/FFcast (the original I believe)
- https://github.com/minos-org/ffcast

I believe they have an option to select a screen region using the mouse or select a running application and crop the region to it (with or without padding).

**Comment by cytopia** [comment]
Looks like there is still some work to be done on it. The cases I have identified so far are:

* Record the whole monitor
* Record all monitors
* Record a selection (selectable via mouse)
* Record a window (click on a window via the mouse)

The examples you posted (especially, the original) are pretty good to get some ideas from.

Anyway I guess the whole thing will be a major change and requires some time for planning, as I also want to support others operating systems like osx, linux and bsd.

**Comment by strages** [comment]
Hi I thought back to this project when i saw a perfect implementation of this concept by cloudapp. This is ultimately how it should be ;)

see the following screencast!

![screencast](https://cloud.githubusercontent.com/assets/429659/14770168/1fc276cc-0a6b-11e6-9090-a7cd7979cf91.gif)

btw is there an error with ffscreencast not casting the mouse?

output to gif would be incredible!

**Comment by cytopia** [comment]
Added for future reference:

Get window dimensions:

* Linux: `xwininfo`
* OSX: TODO
* BSD: `xwininfo`

**Comment by dimitrieh** [comment]
@cytopia btw if you can figure out how to get xrectsel installed on osx, you could use this: https://github.com/lolilolicon/xrectsel

it has problems with libx11

**Comment by cytopia** [comment]
@dimitrieh I guess it has to be something native on OSX, otherwise it will be too bothering for users to deal with it.

If somebody is willing to help with `osascript` or other native osx stuff, I can implement at least the select-window task.

**Comment by cytopia** [comment]
@dimitrieh This will be addressed in #23. Please have a look there.
