### ISSUE TITLE
Homebrew mac ffmpeg does not include libfaac

### ISSUE THREAD

**Issue by NelsonMinar** [cytopia/ffscreencast#6]
Not a bug in ffscreencast, more of a heads' up: Homebrew on the Mac installs ffmpeg without libfaac by default, for license reasons. I believe your audio support assumes that codec is available. It's easy enough to fix in Homebrew with `brew reinstall ffmpeg --with-faac`.

(I was trying to use ffscreencast to record Mac system audio using the kernel extension Soundflower to provide an audio loopback device. Not working so far, but then Soundflower seldom works for me in any context!)

**Comment by cytopia** [comment]
This is a good point.
`libfaac` is the default as can be seen in the config file `~/.config/ffscreencast/ffscreencastrc`:
```shell
...
# Default audio output codec
# Alternatively: 'pcm_s16le'
OUTPUT_ACODEC="libfaac"
...
```
 
If sound is enabled (which it is not by default), `ffscreencast` should probably check if the desired codec is compiled into `ffmpeg`.

As the above output codec can be changed to whatever codec you want to use, I will probably need a more general solution.

Is there a list out there what output audio codecs can be used by `ffmpeg`?

**Comment by NelsonMinar** [comment]
I put a list of all the codecs my Homebrew copy has here: https://gist.github.com/NelsonMinar/54fd4bb1f239d49571b2

**Comment by cytopia** [comment]
I added the stuff to brew and it now required ffmpeg with `with-x265` and `with-faac`.
This should solve it
