### ISSUE TITLE
[Feature] gif output option

### ISSUE THREAD

**Issue by dimitrieh** [cytopia/ffscreencast#9]
It would be incredible to have this be able to output gifs! :)

```
Output options:
-e<ext>           Output video format extension (Default: mkv)
                  E.g.: -emkv, or -eavi, or -emp4, or -gif
```

some interesting links:
- https://github.com/dergachev/screengif
- https://gist.github.com/dergachev/4627207
- https://github.com/minimaxir/video-to-gif-osx

**Comment by cytopia** [comment]
I was already also thinking about creating a preset for gif output. The problem however is, that the quality might not be as good as expected.

If you record your screen with a very good quality first and then convert it to a gif, you can get much better quality out of this.

The main reason for doing the second on is, that you can create your gif in a 2-pass encoding. The first pass will extract the color palette used and then the second pass will apply that color palette to the actual encoding.

I have included such a converter in my **[thunar-custom-actions](https://github.com/cytopia/thunar-custom-actions)** repository (`thunar-video-to-gif.sh`). This script can be used with a gui (`zenity` required) or purely on the command-line (specify with `-c`).

**Comment by dimitrieh** [comment]
Hi nice to know you're thinking on this. Wouldn't it be possible to save it as vid first, with an optional/additional/replacement conversion to gif.

So output would first be only a video file, but the command is not immidiately done, as it converts after to gif, with maybe deleting the original vid file.

**Comment by cytopia** [comment]
I could implement some sort of `post-processing` options with predefined presets for example for:

* gif
* iphone/android
* telegram
* etc.

So it could convert it afterwards.
Deletion of the original video is better left to the user him/herself :-)

**Comment by dimitrieh** [comment]
Would be perfect:) also output options for amount frames/quality/resolution
would be great^^ *acting spoiled*😂

Op do 19 mei 2016 22:36 schreef cytopia <notifications@github.com>:

> I could implement some sort of post-processing options with predefined
> presets for example for:
>
>    - gif
>    - iphone/android
>    - telegram
>    - etc.
>
> So it could convert it afterwards.
> Deletion of the original video is better left to the user him/herself :-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cytopia/ffscreencast/issues/9#issuecomment-220440772>
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by cytopia** [comment]
I added some scripts which now reside [contrib](contrib/) folder that will do the post conversion afterwards. Done in  #19
